### ISSUE TITLE
Missed `objc` method modifier for some methods 

### ISSUE THREAD

**Issue by matsotaa** [aidevjoe/SandboxBrowser#5]
Hey mate, can you please `@objc` modifier for two method in your pod. It would great)
`SandboxBrowser.swift` file, lines 132 & 140

<img width="1169" alt="Screenshot 2023-03-09 at 21 06 31" src="https://user-images.githubusercontent.com/59237122/224129059-8294bfe7-8b17-4e71-8a68-162120b0a84e.png">
<img width="1167" alt="Screenshot 2023-03-09 at 21 06 42" src="https://user-images.githubusercontent.com/59237122/224129098-47540ec8-7918-4fe8-8482-6c7745b9bec8.png">

**Comment by aidevjoe** [comment]
The new version has been released
